# @schema type:[integer];minimum: 1
# -- The number of replicas of the deployment
replicaCount: 1

# @schema additionalProperties: false
# -- Configure the image used by the deployment
image:
  # @schema type:[string]
  repository: nginx
  # @schema enum:[IfNotPresent, Always, Never]
  pullPolicy: IfNotPresent
  # @schema type:[string]
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""
  # @schema type:[string]
  # --  Specify an optional secret with the registry authentication token
  token: ""

# @schema additionalProperties: false
# -- Override the entrypoint and args
entrypoint:
  # @schema item: string
  command: []
  # @schema item: string
  args: []

# @schema additionalProperties: false
serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # @schema additionalProperties: {type: string}
  # -- Annotations to add to the service account
  annotations: {}
  # @schema type:[string]
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: ""

# @schema additionalProperties: {type: string}
podAnnotations: {}

# @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.PodSecurityContext
podSecurityContext: {}

# @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.SecurityContext
securityContext: {}

# @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.Lifecycle
lifecycle: {}

# @schema additionalProperties: false
# -- Configure the service
service:
  # -- Specifies whether or not to create a service
  enabled: true
  # @schema enum:[ExternalName, ClusterIP, NodePort, and LoadBalancer];default: ClusterIP
  # -- Specifies the type of the service
  type: ClusterIP
  # @schema type:[integer]
  # -- Specifies the port of the service
  port: 80
  # @schema type:[string]
  # -- Specifies the name of the port
  portName: http

  # @schema itemRef: file://schemas/service_additional_ports.schema.json
  # -- Specify any additional ports for the service
  additionalPorts: []

  # @schema additionalProperties: false
  # -- Optionally configure properties for an additional LoadBalancer service
  loadBalancer:
    # -- Specifies whether to create an additional service with type LoadBalancer
    enabled: false
    # @schema type:[string]
    # Specify the IP the LoadBalancer should use, leave empty for automatic assignment
    ip: ""
    # @schema enum:[Cluster, Local]
    # -- Specify the externalTrafficPolicy of the service
    externalTrafficPolicy: Cluster

# @schema additionalProperties: false
# -- Configure probes for the deployment
probes:
  # -- Specifies whether or not to add probes to the deployment
  enabled: true

  # @schema enum:[httpGet, tcpSocket, exec]
  # -- Specify the probe type
  type: httpGet

  # @schema $ref: file://schemas/probes_options.schema.json
  # -- Configure options for the probe kind
  options:
    path: /
    port: http

  # schema type:[integer]
  initialDelaySeconds: 0

  # schema type:[integer]
  periodSeconds: 10

  # schema type:[integer]
  timeoutSeconds: 1

  # schema type:[integer]
  successThreshold: 1

  # schema type:[integer]
  failureThreshold: 1

# @schema additionalProperties: false
# -- Setup ServiceMonitors for the deployment
metrics:
  enabled: false

  # @schema type:[string]
  path: /metrics

  # @schema type:[string]
  interval: 60s

  # @schema type:[string]
  timeout: 30s

  # @schema type:[string, integer]
  port: http

  honorLabels: false

# @schema additionalProperties: false
# -- Configure Ingress resources for the service
ingress:
  # -- Specify whether to enable the ingress
  enabled: false

  # @schema type:[string]
  # -- Specify the className of the ingress
  className: "nginx"

  # @schema additionalProperties: {type: string}
  annotations:
    kubernetes.io/tls-acme: "true"

  # @schema itemRef: $k8s/_definitions.json#/definitions/io.k8s.api.networking.v1.IngressRule
  hosts: []

  # @schema itemRef: $k8s/_definitions.json#/definitions/io.k8s.api.networking.v1.IngressTLS
  tls: []

# @schema additionalProperties: false
# -- Configure HTTPRoute resources for the service
httpRoute:
  enabled: false

  # @schema additionalProperties: {type: string}
  labels: {}

  # @schema additionalProperties: {type: string}
  annotations: {}

  # @schema item: string
  # -- The hostnames the route listens on
  hostnames: []

  # @schema itemRef: https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/gateway.networking.k8s.io/httproute_v1.json#/properties/spec/properties/parentRefs/items/properties
  parentRefs: []

  # @schema itemRef: file://schemas/http_route_rules.schema.json
  rules: []

# @schema $ref: $k8s/_definitions.json#definitions/io.k8s.api.core.v1.ResourceRequirements
resources: {}

# @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.NodeSelector/properties
nodeSelector: {}

# @schema itemRef: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.Toleration
tolerations: []

# @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.Affinity
affinity: {}

# @schema additionalProperties: false
deploymentStrategy:
  # @schema enum:[RollingUpdate, Recreate]
  type: RollingUpdate

# @schema additionalProperties: false
pvc:
  # -- Specifies whether to create a PVC
  enabled: false

  # @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.apimachinery.pkg.api.resource.Quantity
  # -- Specify the size of the PVC
  size: 1Gi

  # @schema type:[string]
  # -- Specify the storageclass of the pvc
  storageClassName: smb

  # @schema item: string
  # -- Specify the access modes for the pvc
  accessModes: [ReadWriteOnce]

  # -- Specify the path in the container to mount the pvc
  mountPath: /data

# @schema additionalProperties: {type: string}
# -- Specify any values to add to the configmap
config: {}

# @schema additionalProperties: false
# -- The external-secrets item
secrets:
  # -- Specify whether to create an external-secrets item
  enabled: false

  # @schema additionalProperties: false
  secretStoreRef:
    # @schema enum:[SecretStore, ClusterSecretStore]
    kind: ClusterSecretStore

    # @schema type:[string]
    name: onepassword-connect

  # -- Specify the key external-secrets shoudl pull data form
  key: ""

# @schema itemRef: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.Volume
# -- Specify any additional volumes
volumes: []

# @schema itemRef: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.VolumeMount
# -- Specify any additional volume mounts
volumeMounts: []

# @schema itemRef: file://schemas/pod_additional_port.schema.json
# -- Specify any addtional ports on the container
additionalPorts: []

# @schema itemRef: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.Container
# -- Specify any initContainer for the pod
initContainers: []

# @schema itemRef: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.Container
# -- Specify any extra container in the pod
extraContainers: []

# @schema itemRef: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.EnvVar
# -- Specify any extra env fields
env: []

# Specify any jobs to deploy
jobs: []

# @schema additionalProperties: false
# -- Add a sidecar that connects to a wireguard vpn and routes pod traffic through it
vpn:
  # -- Specify whether to enable a VPN sidecar
  enabled: false

  # @schema additionalProperties: false
  probes:
    enabled: true

    # @schema item: string
    exec:
      - sh
      - -c
      - curl https://am.i.mullvad.net/connected | grep "You are connected"

  # @schema additionalProperties: false
  image:
    repository: linuxserver/wireguard

    # @schema enum:[IfNotPresent, Always, Never]
    pullPolicy: Always

    tag: latest

  # @schema $ref: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.PodSecurityContext
  securityContext:
    capabilities: { add: ["NET_ADMIN"] }
    privileged: true

  # @schema itemRef: $k8s/_definitions.json#/definitions/io.k8s.api.core.v1.EnvVar
  env:
    - name: PUID
      value: "911"
    - name: PGID
      value: "911"

  # -- Scripts to run to copy over the wirguard config
  script: |
    echo Copying config file to shared volume
    cp /wg/wg0.conf /config/wg0.conf

  # @schema additionalProperties: false
  # -- external-secrets config for the wireguard secret
  secret:
    # Specify whether to create an external secrets resource for the vpn config
    enabled: true

    # @schema additionalProperties: false
    secretStoreRef:
      # @schema enum:[ClusterSecretStore, SecretStore]
      kind: ClusterSecretStore

      name: onepassword-connect
    # -- The key external secrets uses to pull in the wireguard configs
    key: "wg0.conf"

    # @schema additionalProperties: false
    mount:
      # -- Specify whether to mount the secret in to container
      enabled: true
      # -- Specify the path to mount the secret to
      path: /config/wg_confs

# @schema additionalProperties: false
# -- Configure a NetworkPolicy for the app
netpol:
  enabled: false

  # @schema
  # -- When true, automatically adds an egress rule to kube-system coredns pods
  allowCoredns: true

  # @schema itemRef: $k8s/_definitions.json#/definitions/io.k8s.api.networking.v1.NetworkPolicySpec/properties/ingress/items
  ingress: []

  # @schema itemRef: $k8s/_definitions.json#/definitions/io.k8s.api.networking.v1.NetworkPolicySpec/properties/egress/items
  egress: []
