{{- $global := . -}}
{{- range $job := .Values.jobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $job.name }}
  {{- if $job.annotations }}
  annotations:
    {{- $job.annotations | toYaml | nindent 4 }}
  {{- end }}
  labels:
    {{- include "generic.labels" $global | nindent 4 }}
    {{- if $job.labels }}
    {{- $job.labels | toYaml | nindent 4 }}
    {{- end }}
spec:
  ttlSecondsAfterFinished: {{ default 0 $job.ttlSecondsAfterFinished }}
  template:
    spec:
      containers:
      {{- range $container := $job.containers }}
        - name: {{ $container.name }}
          image: {{ $container.image }}
          command: 
            {{- $container.command | toYaml | nindent 12 }}
          {{- if $container.env }}
          env:
            {{- $container.env | toYaml | nindent 12 }}
          {{- end }}
          {{- if and ($container.envFrom) (gt 0 (len $container.envFrom)) }}
          envFrom:
            {{- $container.envFrom | toYaml | nindent 12 }}
          {{- end }}
      {{- end }}
      restartPolicy: {{ default "Never" $job.restartPolicy }}
  backoffLimit: {{  default 3 $job.backoffLimit }}
{{- end }}
