{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "generic.fullname" . }}
spec:
  secretStoreRef:
    {{- .Values.secrets.secretStoreRef | toYaml | nindent 4 }}
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.secrets.key }}
{{- end }}
