apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "generic.labels" . | nindent 4 }}
  name: {{ include "generic.fullname" . }}
spec:
  endpoints:
    - honorLabels: {{ .Values.metrics.honorLabels }}
      interval: {{ .Values.metrics.interval }}
      path: {{ .Values.metrics.path }}
      scrapeTimeout: {{ .Values.metrics.timeout }}
      port: {{ .Values.metrics.port }}
  namespaceSelector:
    matchNames:
        - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "generic.selectorLabels" . | nindent 6 }}
