{{- if and (.Values.vpn.enabled) (.Values.vpn.secret.enabled) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "generic.fullname" . }}-wireguard
spec:
  secretStoreRef:
    {{- .Values.vpn.secret.secretStoreRef | toYaml | nindent 4 }}
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.vpn.secret.key }}
{{- end }}